name: country_code_picker_plus
version: 0.1.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:

  uses-material-design: true

  assets:
    - assets/countries.json
    - assets/i18n/
    - assets/flags/