name: bardix
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # for navigation
  go_router: ^13.2.0

  animated_splash_screen: ^1.3.0
  # local database
  shared_preferences: ^2.2.3

  # dependency injection
  get_it: ^8.0.3

  # Images
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  country_code_picker_plus:
    path: packages/country_code_picker_plus-0.1.0+1
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_gen_runner:
  build_runner:

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - lib/l10n/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
