const List<Map<String, String>> countryCodes = [
  {
    "num_code": "682",
    "alpha_2_code": "SA",
    "alpha_3_code": "SAU",
    "en_short_name": "Saudi Arabia",
    "nationality": "Saudi, Saudi Arabian",
    "dial_code": "+966",
    "ar_name": "السعودية"
  },
  {
    "num_code": "4",
    "alpha_2_code": "AF",
    "alpha_3_code": "AFG",
    "en_short_name": "Afghanistan",
    "nationality": "Afghan",
    "dial_code": "+93",
    "ar_name": "أفغانستان"
  },
  {
    "num_code": "248",
    "alpha_2_code": "AX",
    "alpha_3_code": "ALA",
    "en_short_name": "Åland Islands",
    "nationality": "Åland Island",
    "dial_code": "+358",
    "ar_name": "جزر أولاند"
  },
  {
    "num_code": "8",
    "alpha_2_code": "AL",
    "alpha_3_code": "ALB",
    "en_short_name": "Albania",
    "nationality": "Albanian",
    "dial_code": "+355",
    "ar_name": "ألبانيا"
  },
  {
    "num_code": "12",
    "alpha_2_code": "DZ",
    "alpha_3_code": "DZA",
    "en_short_name": "Algeria",
    "nationality": "Algerian",
    "dial_code": "+213",
    "ar_name": "الجزائر"
  },
  {
    "num_code": "16",
    "alpha_2_code": "AS",
    "alpha_3_code": "ASM",
    "en_short_name": "American Samoa",
    "nationality": "American Samoan",
    "dial_code": "+1684",
    "ar_name": "ساموا الأمريكية"
  },
  {
    "num_code": "20",
    "alpha_2_code": "AD",
    "alpha_3_code": "AND",
    "en_short_name": "Andorra",
    "nationality": "Andorran",
    "dial_code": "+376",
    "ar_name": "أندورا"
  },
  {
    "num_code": "24",
    "alpha_2_code": "AO",
    "alpha_3_code": "AGO",
    "en_short_name": "Angola",
    "nationality": "Angolan",
    "dial_code": "+244",
    "ar_name": "أنغولا"
  },
  {
    "num_code": "660",
    "alpha_2_code": "AI",
    "alpha_3_code": "AIA",
    "en_short_name": "Anguilla",
    "nationality": "Anguillan",
    "dial_code": "+1264",
    "ar_name": "أنغويلا"
  },
  {
    "num_code": "10",
    "alpha_2_code": "AQ",
    "alpha_3_code": "ATA",
    "en_short_name": "Antarctica",
    "nationality": "Antarctic",
    "dial_code": "+672",
    "ar_name": "القارة القطبية الجنوبية"
  },
  {
    "num_code": "28",
    "alpha_2_code": "AG",
    "alpha_3_code": "ATG",
    "en_short_name": "Antigua and Barbuda",
    "nationality": "Antiguan or Barbudan",
    "dial_code": "+1268",
    "ar_name": "أنتيغوا وباربودا"
  },
  {
    "num_code": "32",
    "alpha_2_code": "AR",
    "alpha_3_code": "ARG",
    "en_short_name": "Argentina",
    "nationality": "Argentine",
    "dial_code": "+54",
    "ar_name": "الأرجنتين"
  },
  {
    "num_code": "51",
    "alpha_2_code": "AM",
    "alpha_3_code": "ARM",
    "en_short_name": "Armenia",
    "nationality": "Armenian",
    "dial_code": "+374",
    "ar_name": "أرمينيا"
  },
  {
    "num_code": "533",
    "alpha_2_code": "AW",
    "alpha_3_code": "ABW",
    "en_short_name": "Aruba",
    "nationality": "Aruban",
    "dial_code": "+297",
    "ar_name": "أروبا"
  },
  {
    "num_code": "36",
    "alpha_2_code": "AU",
    "alpha_3_code": "AUS",
    "en_short_name": "Australia",
    "nationality": "Australian",
    "dial_code": "+61",
    "ar_name": "أستراليا"
  },
  {
    "num_code": "40",
    "alpha_2_code": "AT",
    "alpha_3_code": "AUT",
    "en_short_name": "Austria",
    "nationality": "Austrian",
    "dial_code": "+43",
    "ar_name": "النمسا"
  },
  {
    "num_code": "31",
    "alpha_2_code": "AZ",
    "alpha_3_code": "AZE",
    "en_short_name": "Azerbaijan",
    "nationality": "Azerbaijani, Azeri",
    "dial_code": "+994",
    "ar_name": "أذربيجان"
  },
  {
    "num_code": "44",
    "alpha_2_code": "BS",
    "alpha_3_code": "BHS",
    "en_short_name": "Bahamas",
    "nationality": "Bahamian",
    "dial_code": "+1242",
    "ar_name": "باهاماس"
  },
  {
    "num_code": "48",
    "alpha_2_code": "BH",
    "alpha_3_code": "BHR",
    "en_short_name": "Bahrain",
    "nationality": "Bahraini",
    "dial_code": "+973",
    "ar_name": "البحرين"
  },
  {
    "num_code": "50",
    "alpha_2_code": "BD",
    "alpha_3_code": "BGD",
    "en_short_name": "Bangladesh",
    "nationality": "Bangladeshi",
    "dial_code": "+880",
    "ar_name": "بنغلاديش"
  },
  {
    "num_code": "52",
    "alpha_2_code": "BB",
    "alpha_3_code": "BRB",
    "en_short_name": "Barbados",
    "nationality": "Barbadian",
    "dial_code": "+1246",
    "ar_name": "باربادوس"
  },
  {
    "num_code": "112",
    "alpha_2_code": "BY",
    "alpha_3_code": "BLR",
    "en_short_name": "Belarus",
    "nationality": "Belarusian",
    "dial_code": "+375",
    "ar_name": "روسيا البيضاء"
  },
  {
    "num_code": "56",
    "alpha_2_code": "BE",
    "alpha_3_code": "BEL",
    "en_short_name": "Belgium",
    "nationality": "Belgian",
    "dial_code": "+32",
    "ar_name": "بلجيكا"
  },
  {
    "num_code": "84",
    "alpha_2_code": "BZ",
    "alpha_3_code": "BLZ",
    "en_short_name": "Belize",
    "nationality": "Belizean",
    "dial_code": "+501",
    "ar_name": "بليز"
  },
  {
    "num_code": "204",
    "alpha_2_code": "BJ",
    "alpha_3_code": "BEN",
    "en_short_name": "Benin",
    "nationality": "Beninese, Beninois",
    "dial_code": "+229",
    "ar_name": "بنين"
  },
  {
    "num_code": "60",
    "alpha_2_code": "BM",
    "alpha_3_code": "BMU",
    "en_short_name": "Bermuda",
    "nationality": "Bermudian, Bermudan",
    "dial_code": "+1441",
    "ar_name": "برمودا"
  },
  {
    "num_code": "64",
    "alpha_2_code": "BT",
    "alpha_3_code": "BTN",
    "en_short_name": "Bhutan",
    "nationality": "Bhutanese",
    "dial_code": "+975",
    "ar_name": "بوتان"
  },
  {
    "num_code": "68",
    "alpha_2_code": "BO",
    "alpha_3_code": "BOL",
    "en_short_name": "Bolivia (Plurinational State of)",
    "nationality": "Bolivian",
    "dial_code": "+591",
    "ar_name": "بوليفيا"
  },
  {
    "num_code": "70",
    "alpha_2_code": "BA",
    "alpha_3_code": "BIH",
    "en_short_name": "Bosnia and Herzegovina",
    "nationality": "Bosnian or Herzegovinian",
    "dial_code": "+387",
    "ar_name": "البوسنة والهرسك"
  },
  {
    "num_code": "72",
    "alpha_2_code": "BW",
    "alpha_3_code": "BWA",
    "en_short_name": "Botswana",
    "nationality": "Motswana, Botswanan",
    "dial_code": "+267",
    "ar_name": "بوتسوانا"
  },
  {
    "num_code": "74",
    "alpha_2_code": "BV",
    "alpha_3_code": "BVT",
    "en_short_name": "Bouvet Island",
    "nationality": "Bouvet Island",
    "dial_code": "+47",
    "ar_name": "جزيرة بوفيه"
  },
  {
    "num_code": "76",
    "alpha_2_code": "BR",
    "alpha_3_code": "BRA",
    "en_short_name": "Brazil",
    "nationality": "Brazilian",
    "dial_code": "+55",
    "ar_name": "البرازيل"
  },
  {
    "num_code": "86",
    "alpha_2_code": "IO",
    "alpha_3_code": "IOT",
    "en_short_name": "British Indian Ocean Territory",
    "nationality": "BIOT",
    "dial_code": "+246",
    "ar_name": "إقليم المحيط الهندي البريطاني"
  },
  {
    "num_code": "96",
    "alpha_2_code": "BN",
    "alpha_3_code": "BRN",
    "en_short_name": "Brunei Darussalam",
    "nationality": "Bruneian",
    "dial_code": "+673",
    "ar_name": "بروناي"
  },
  {
    "num_code": "100",
    "alpha_2_code": "BG",
    "alpha_3_code": "BGR",
    "en_short_name": "Bulgaria",
    "nationality": "Bulgarian",
    "dial_code": "+359",
    "ar_name": "بلغاريا"
  },
  {
    "num_code": "854",
    "alpha_2_code": "BF",
    "alpha_3_code": "BFA",
    "en_short_name": "Burkina Faso",
    "nationality": "Burkinabé",
    "dial_code": "+226",
    "ar_name": "بوركينا فاسو"
  },
  {
    "num_code": "108",
    "alpha_2_code": "BI",
    "alpha_3_code": "BDI",
    "en_short_name": "Burundi",
    "nationality": "Burundian",
    "dial_code": "+257",
    "ar_name": "بوروندي"
  },
  {
    "num_code": "132",
    "alpha_2_code": "CV",
    "alpha_3_code": "CPV",
    "en_short_name": "Cabo Verde",
    "nationality": "Cabo Verdean",
    "dial_code": "+238",
    "ar_name": "الرأس الأخضر"
  },
  {
    "num_code": "116",
    "alpha_2_code": "KH",
    "alpha_3_code": "KHM",
    "en_short_name": "Cambodia",
    "nationality": "Cambodian",
    "dial_code": "+855",
    "ar_name": "كمبوديا"
  },
  {
    "num_code": "120",
    "alpha_2_code": "CM",
    "alpha_3_code": "CMR",
    "en_short_name": "Cameroon",
    "nationality": "Cameroonian",
    "dial_code": "+237",
    "ar_name": "الكاميرون"
  },
  {
    "num_code": "124",
    "alpha_2_code": "CA",
    "alpha_3_code": "CAN",
    "en_short_name": "Canada",
    "nationality": "Canadian",
    "dial_code": "+1",
    "ar_name": "كندا"
  },
  {
    "num_code": "136",
    "alpha_2_code": "KY",
    "alpha_3_code": "CYM",
    "en_short_name": "Cayman Islands",
    "nationality": "Caymanian",
    "dial_code": "+ 345",
    "ar_name": "جزر كايمان"
  },
  {
    "num_code": "140",
    "alpha_2_code": "CF",
    "alpha_3_code": "CAF",
    "en_short_name": "Central African Republic",
    "nationality": "Central African",
    "dial_code": "+236",
    "ar_name": "جمهورية أفريقيا الوسطى"
  },
  {
    "num_code": "148",
    "alpha_2_code": "TD",
    "alpha_3_code": "TCD",
    "en_short_name": "Chad",
    "nationality": "Chadian",
    "dial_code": "+235",
    "ar_name": "تشاد"
  },
  {
    "num_code": "152",
    "alpha_2_code": "CL",
    "alpha_3_code": "CHL",
    "en_short_name": "Chile",
    "nationality": "Chilean",
    "dial_code": "+56",
    "ar_name": "تشيلي"
  },
  {
    "num_code": "156",
    "alpha_2_code": "CN",
    "alpha_3_code": "CHN",
    "en_short_name": "China",
    "nationality": "Chinese",
    "dial_code": "+86",
    "ar_name": "الصين"
  },
  {
    "num_code": "162",
    "alpha_2_code": "CX",
    "alpha_3_code": "CXR",
    "en_short_name": "Christmas Island",
    "nationality": "Christmas Island",
    "dial_code": "+61",
    "ar_name": "جزيرة عيد الميلاد"
  },
  {
    "num_code": "166",
    "alpha_2_code": "CC",
    "alpha_3_code": "CCK",
    "en_short_name": "Cocos (Keeling) Islands",
    "nationality": "Cocos Island",
    "dial_code": "+61",
    "ar_name": "جزر كوكوس"
  },
  {
    "num_code": "170",
    "alpha_2_code": "CO",
    "alpha_3_code": "COL",
    "en_short_name": "Colombia",
    "nationality": "Colombian",
    "dial_code": "+57",
    "ar_name": "كولومبيا"
  },
  {
    "num_code": "174",
    "alpha_2_code": "KM",
    "alpha_3_code": "COM",
    "en_short_name": "Comoros",
    "nationality": "Comoran, Comorian",
    "dial_code": "+269",
    "ar_name": "جزر القمر"
  },
  {
    "num_code": "178",
    "alpha_2_code": "CG",
    "alpha_3_code": "COG",
    "en_short_name": "Congo (Republic of the)",
    "nationality": "Congolese",
    "dial_code": "+242",
    "ar_name": "جمهورية الكونغو"
  },
  {
    "num_code": "180",
    "alpha_2_code": "CD",
    "alpha_3_code": "COD",
    "en_short_name": "Congo (Democratic Republic of the)",
    "nationality": "Congolese",
    "dial_code": "+243",
    "ar_name": "جمهورية الكونغو الديمقراطية"
  },
  {
    "num_code": "184",
    "alpha_2_code": "CK",
    "alpha_3_code": "COK",
    "en_short_name": "Cook Islands",
    "nationality": "Cook Island",
    "dial_code": "+682",
    "ar_name": "جزر كوك"
  },
  {
    "num_code": "188",
    "alpha_2_code": "CR",
    "alpha_3_code": "CRI",
    "en_short_name": "Costa Rica",
    "nationality": "Costa Rican",
    "dial_code": "+506",
    "ar_name": "كوستاريكا"
  },
  {
    "num_code": "384",
    "alpha_2_code": "CI",
    "alpha_3_code": "CIV",
    "en_short_name": "Côte d'Ivoire",
    "nationality": "Ivorian",
    "dial_code": "+225",
    "ar_name": "ساحل العاج"
  },
  {
    "num_code": "191",
    "alpha_2_code": "HR",
    "alpha_3_code": "HRV",
    "en_short_name": "Croatia",
    "nationality": "Croatian",
    "dial_code": "+385",
    "ar_name": "كرواتيا"
  },
  {
    "num_code": "192",
    "alpha_2_code": "CU",
    "alpha_3_code": "CUB",
    "en_short_name": "Cuba",
    "nationality": "Cuban",
    "dial_code": "+53",
    "ar_name": "كوبا"
  },
  {
    "num_code": "196",
    "alpha_2_code": "CY",
    "alpha_3_code": "CYP",
    "en_short_name": "Cyprus",
    "nationality": "Cypriot",
    "dial_code": "+357",
    "ar_name": "قبرص"
  },
  {
    "num_code": "203",
    "alpha_2_code": "CZ",
    "alpha_3_code": "CZE",
    "en_short_name": "Czech Republic",
    "nationality": "Czech",
    "dial_code": "+420",
    "ar_name": "جمهورية التشيك"
  },
  {
    "num_code": "208",
    "alpha_2_code": "DK",
    "alpha_3_code": "DNK",
    "en_short_name": "Denmark",
    "nationality": "Danish",
    "dial_code": "+45",
    "ar_name": "الدنمارك"
  },
  {
    "num_code": "262",
    "alpha_2_code": "DJ",
    "alpha_3_code": "DJI",
    "en_short_name": "Djibouti",
    "nationality": "Djiboutian",
    "dial_code": "+253",
    "ar_name": "جيبوتي"
  },
  {
    "num_code": "212",
    "alpha_2_code": "DM",
    "alpha_3_code": "DMA",
    "en_short_name": "Dominica",
    "nationality": "Dominican",
    "dial_code": "+1767",
    "ar_name": "دومينيكا"
  },
  {
    "num_code": "214",
    "alpha_2_code": "DO",
    "alpha_3_code": "DOM",
    "en_short_name": "Dominican Republic",
    "nationality": "Dominican",
    "dial_code": "+1849",
    "ar_name": "جمهورية الدومينيكان"
  },
  {
    "num_code": "218",
    "alpha_2_code": "EC",
    "alpha_3_code": "ECU",
    "en_short_name": "Ecuador",
    "nationality": "Ecuadorian",
    "dial_code": "+593",
    "ar_name": "الإكوادور"
  },
  {
    "num_code": "818",
    "alpha_2_code": "EG",
    "alpha_3_code": "EGY",
    "en_short_name": "Egypt",
    "nationality": "Egyptian",
    "dial_code": "+20",
    "ar_name": "مصر"
  },
  {
    "num_code": "222",
    "alpha_2_code": "SV",
    "alpha_3_code": "SLV",
    "en_short_name": "El Salvador",
    "nationality": "Salvadoran",
    "dial_code": "+503",
    "ar_name": "السلفادور"
  },
  {
    "num_code": "226",
    "alpha_2_code": "GQ",
    "alpha_3_code": "GNQ",
    "en_short_name": "Equatorial Guinea",
    "nationality": "Equatorial Guinean, Equatoguinean",
    "dial_code": "+240",
    "ar_name": "غينيا الاستوائية"
  },
  {
    "num_code": "232",
    "alpha_2_code": "ER",
    "alpha_3_code": "ERI",
    "en_short_name": "Eritrea",
    "nationality": "Eritrean",
    "dial_code": "+291",
    "ar_name": "إريتريا"
  },
  {
    "num_code": "233",
    "alpha_2_code": "EE",
    "alpha_3_code": "EST",
    "en_short_name": "Estonia",
    "nationality": "Estonian",
    "dial_code": "+372",
    "ar_name": "إستونيا"
  },
  {
    "num_code": "231",
    "alpha_2_code": "ET",
    "alpha_3_code": "ETH",
    "en_short_name": "Ethiopia",
    "nationality": "Ethiopian",
    "dial_code": "+251",
    "ar_name": "إثيوبيا"
  },
  {
    "num_code": "238",
    "alpha_2_code": "FK",
    "alpha_3_code": "FLK",
    "en_short_name": "Falkland Islands (Malvinas)",
    "nationality": "Falkland Island",
    "dial_code": "+500",
    "ar_name": "جزر فوكلاند"
  },
  {
    "num_code": "234",
    "alpha_2_code": "FO",
    "alpha_3_code": "FRO",
    "en_short_name": "Faroe Islands",
    "nationality": "Faroese",
    "dial_code": "+298",
    "ar_name": "جزر فارو"
  },
  {
    "num_code": "242",
    "alpha_2_code": "FJ",
    "alpha_3_code": "FJI",
    "en_short_name": "Fiji",
    "nationality": "Fijian",
    "dial_code": "+679",
    "ar_name": "فيجي"
  },
  {
    "num_code": "246",
    "alpha_2_code": "FI",
    "alpha_3_code": "FIN",
    "en_short_name": "Finland",
    "nationality": "Finnish",
    "dial_code": "+358",
    "ar_name": "فنلندا"
  },
  {
    "num_code": "250",
    "alpha_2_code": "FR",
    "alpha_3_code": "FRA",
    "en_short_name": "France",
    "nationality": "French",
    "dial_code": "+33",
    "ar_name": "فرنسا"
  },
  {
    "num_code": "254",
    "alpha_2_code": "GF",
    "alpha_3_code": "GUF",
    "en_short_name": "French Guiana",
    "nationality": "French Guianese",
    "dial_code": "+594",
    "ar_name": "غويانا الفرنسية"
  },
  {
    "num_code": "258",
    "alpha_2_code": "PF",
    "alpha_3_code": "PYF",
    "en_short_name": "French Polynesia",
    "nationality": "French Polynesian",
    "dial_code": "+689",
    "ar_name": "بولينزيا الفرنسية"
  },
  {
    "num_code": "260",
    "alpha_2_code": "TF",
    "alpha_3_code": "ATF",
    "en_short_name": "French Southern Territories",
    "nationality": "French Southern Territories",
    "dial_code": "+262",
    "ar_name": "أراض فرنسية جنوبية وأنتارتيكية"
  },
  {
    "num_code": "266",
    "alpha_2_code": "GA",
    "alpha_3_code": "GAB",
    "en_short_name": "Gabon",
    "nationality": "Gabonese",
    "dial_code": "+241",
    "ar_name": "الغابون"
  },
  {
    "num_code": "270",
    "alpha_2_code": "GM",
    "alpha_3_code": "GMB",
    "en_short_name": "Gambia",
    "nationality": "Gambian",
    "dial_code": "+220",
    "ar_name": "غامبيا"
  },
  {
    "num_code": "268",
    "alpha_2_code": "GE",
    "alpha_3_code": "GEO",
    "en_short_name": "Georgia",
    "nationality": "Georgian",
    "dial_code": "+995",
    "ar_name": "جورجيا"
  },
  {
    "num_code": "276",
    "alpha_2_code": "DE",
    "alpha_3_code": "DEU",
    "en_short_name": "Germany",
    "nationality": "German",
    "dial_code": "+49",
    "ar_name": "ألمانيا"
  },
  {
    "num_code": "288",
    "alpha_2_code": "GH",
    "alpha_3_code": "GHA",
    "en_short_name": "Ghana",
    "nationality": "Ghanaian",
    "dial_code": "+233",
    "ar_name": "غانا"
  },
  {
    "num_code": "292",
    "alpha_2_code": "GI",
    "alpha_3_code": "GIB",
    "en_short_name": "Gibraltar",
    "nationality": "Gibraltar",
    "dial_code": "+350",
    "ar_name": "جبل طارق"
  },
  {
    "num_code": "300",
    "alpha_2_code": "GR",
    "alpha_3_code": "GRC",
    "en_short_name": "Greece",
    "nationality": "Greek, Hellenic",
    "dial_code": "+30",
    "ar_name": "اليونان"
  },
  {
    "num_code": "304",
    "alpha_2_code": "GL",
    "alpha_3_code": "GRL",
    "en_short_name": "Greenland",
    "nationality": "Greenlandic",
    "dial_code": "+299",
    "ar_name": "جرينلاند"
  },
  {
    "num_code": "308",
    "alpha_2_code": "GD",
    "alpha_3_code": "GRD",
    "en_short_name": "Grenada",
    "nationality": "Grenadian",
    "dial_code": "+1473",
    "ar_name": "غرينادا"
  },
  {
    "num_code": "312",
    "alpha_2_code": "GP",
    "alpha_3_code": "GLP",
    "en_short_name": "Guadeloupe",
    "nationality": "Guadeloupe",
    "dial_code": "+590",
    "ar_name": "غوادلوب"
  },
  {
    "num_code": "316",
    "alpha_2_code": "GU",
    "alpha_3_code": "GUM",
    "en_short_name": "Guam",
    "nationality": "Guamanian, Guambat",
    "dial_code": "+1671",
    "ar_name": "غوام"
  },
  {
    "num_code": "320",
    "alpha_2_code": "GT",
    "alpha_3_code": "GTM",
    "en_short_name": "Guatemala",
    "nationality": "Guatemalan",
    "dial_code": "+502",
    "ar_name": "غواتيمالا"
  },
  {
    "num_code": "831",
    "alpha_2_code": "GG",
    "alpha_3_code": "GGY",
    "en_short_name": "Guernsey",
    "nationality": "Channel Island",
    "dial_code": "+44",
    "ar_name": "غيرنزي"
  },
  {
    "num_code": "324",
    "alpha_2_code": "GN",
    "alpha_3_code": "GIN",
    "en_short_name": "Guinea",
    "nationality": "Guinean",
    "dial_code": "+224",
    "ar_name": "غينيا"
  },
  {
    "num_code": "624",
    "alpha_2_code": "GW",
    "alpha_3_code": "GNB",
    "en_short_name": "Guinea-Bissau",
    "nationality": "Bissau-Guinean",
    "dial_code": "+245",
    "ar_name": "غينيا بيساو"
  },
  {
    "num_code": "328",
    "alpha_2_code": "GY",
    "alpha_3_code": "GUY",
    "en_short_name": "Guyana",
    "nationality": "Guyanese",
    "dial_code": "+592",
    "ar_name": "غيانا"
  },
  {
    "num_code": "332",
    "alpha_2_code": "HT",
    "alpha_3_code": "HTI",
    "en_short_name": "Haiti",
    "nationality": "Haitian",
    "dial_code": "+509",
    "ar_name": "هايتي"
  },
  {
    "num_code": "334",
    "alpha_2_code": "HM",
    "alpha_3_code": "HMD",
    "en_short_name": "Heard Island and McDonald Islands",
    "nationality": "Heard Island or McDonald Islands",
    "dial_code": "+0",
    "ar_name": "جزيرة هيرد وجزر ماكدونالد"
  },
  {
    "num_code": "336",
    "alpha_2_code": "VA",
    "alpha_3_code": "VAT",
    "en_short_name": "Vatican City State",
    "nationality": "Vatican",
    "dial_code": "+379",
    "ar_name": "الفاتيكان"
  },
  {
    "num_code": "340",
    "alpha_2_code": "HN",
    "alpha_3_code": "HND",
    "en_short_name": "Honduras",
    "nationality": "Honduran",
    "dial_code": "+504",
    "ar_name": "هندوراس"
  },
  {
    "num_code": "344",
    "alpha_2_code": "HK",
    "alpha_3_code": "HKG",
    "en_short_name": "Hong Kong",
    "nationality": "Hong Kong, Hong Kongese",
    "dial_code": "+852",
    "ar_name": "هونغ كونغ"
  },
  {
    "num_code": "348",
    "alpha_2_code": "HU",
    "alpha_3_code": "HUN",
    "en_short_name": "Hungary",
    "nationality": "Hungarian, Magyar",
    "dial_code": "+36",
    "ar_name": "المجر"
  },
  {
    "num_code": "352",
    "alpha_2_code": "IS",
    "alpha_3_code": "ISL",
    "en_short_name": "Iceland",
    "nationality": "Icelandic",
    "dial_code": "+354",
    "ar_name": "آيسلندا"
  },
  {
    "num_code": "356",
    "alpha_2_code": "IN",
    "alpha_3_code": "IND",
    "en_short_name": "India",
    "nationality": "Indian",
    "dial_code": "+91",
    "ar_name": "الهند"
  },
  {
    "num_code": "360",
    "alpha_2_code": "ID",
    "alpha_3_code": "IDN",
    "en_short_name": "Indonesia",
    "nationality": "Indonesian",
    "dial_code": "+62",
    "ar_name": "إندونيسيا"
  },
  {
    "num_code": "364",
    "alpha_2_code": "IR",
    "alpha_3_code": "IRN",
    "en_short_name": "Iran",
    "nationality": "Iranian, Persian",
    "dial_code": "+98",
    "ar_name": "إيران"
  },
  {
    "num_code": "368",
    "alpha_2_code": "IQ",
    "alpha_3_code": "IRQ",
    "en_short_name": "Iraq",
    "nationality": "Iraqi",
    "dial_code": "+964",
    "ar_name": "العراق"
  },
  {
    "num_code": "372",
    "alpha_2_code": "IE",
    "alpha_3_code": "IRL",
    "en_short_name": "Ireland",
    "nationality": "Irish",
    "dial_code": "+353",
    "ar_name": "أيرلندا"
  },
  {
    "num_code": "833",
    "alpha_2_code": "IM",
    "alpha_3_code": "IMN",
    "en_short_name": "Isle of Man",
    "nationality": "Manx",
    "dial_code": "+44",
    "ar_name": "جزيرة مان"
  },
  {
    "num_code": "380",
    "alpha_2_code": "IT",
    "alpha_3_code": "ITA",
    "en_short_name": "Italy",
    "nationality": "Italian",
    "dial_code": "+39",
    "ar_name": "إيطاليا"
  },
  {
    "num_code": "388",
    "alpha_2_code": "JM",
    "alpha_3_code": "JAM",
    "en_short_name": "Jamaica",
    "nationality": "Jamaican",
    "dial_code": "+1876",
    "ar_name": "جامايكا"
  },
  {
    "num_code": "392",
    "alpha_2_code": "JP",
    "alpha_3_code": "JPN",
    "en_short_name": "Japan",
    "nationality": "Japanese",
    "dial_code": "+81",
    "ar_name": "اليابان"
  },
  {
    "num_code": "832",
    "alpha_2_code": "JE",
    "alpha_3_code": "JEY",
    "en_short_name": "Jersey",
    "nationality": "Channel Island",
    "dial_code": "+44",
    "ar_name": "جيرزي"
  },
  {
    "num_code": "400",
    "alpha_2_code": "JO",
    "alpha_3_code": "JOR",
    "en_short_name": "Jordan",
    "nationality": "Jordanian",
    "dial_code": "+962",
    "ar_name": "الأردن"
  },
  {
    "num_code": "398",
    "alpha_2_code": "KZ",
    "alpha_3_code": "KAZ",
    "en_short_name": "Kazakhstan",
    "nationality": "Kazakhstani, Kazakh",
    "dial_code": "+7",
    "ar_name": "كازاخستان"
  },
  {
    "num_code": "404",
    "alpha_2_code": "KE",
    "alpha_3_code": "KEN",
    "en_short_name": "Kenya",
    "nationality": "Kenyan",
    "dial_code": "+254",
    "ar_name": "كينيا"
  },
  {
    "num_code": "296",
    "alpha_2_code": "KI",
    "alpha_3_code": "KIR",
    "en_short_name": "Kiribati",
    "nationality": "I-Kiribati",
    "dial_code": "+686",
    "ar_name": "كيريباتي"
  },
  {
    "num_code": "408",
    "alpha_2_code": "KP",
    "alpha_3_code": "PRK",
    "en_short_name": "Korea (Democratic People's Republic of)",
    "nationality": "North Korean",
    "dial_code": "+850",
    "ar_name": "كوريا الشمالية"
  },
  {
    "num_code": "410",
    "alpha_2_code": "KR",
    "alpha_3_code": "KOR",
    "en_short_name": "Korea (Republic of)",
    "nationality": "South Korean",
    "dial_code": "+82",
    "ar_name": "كوريا الجنوبية"
  },
  {
    "num_code": "414",
    "alpha_2_code": "KW",
    "alpha_3_code": "KWT",
    "en_short_name": "Kuwait",
    "nationality": "Kuwaiti",
    "dial_code": "+965",
    "ar_name": "الكويت"
  },
  {
    "num_code": "417",
    "alpha_2_code": "KG",
    "alpha_3_code": "KGZ",
    "en_short_name": "Kyrgyzstan",
    "nationality": "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz",
    "dial_code": "+996",
    "ar_name": "قيرغيزستان"
  },
  {
    "num_code": "418",
    "alpha_2_code": "LA",
    "alpha_3_code": "LAO",
    "en_short_name": "Lao People's Democratic Republic",
    "nationality": "Lao, Laotian",
    "dial_code": "+856",
    "ar_name": "لاوس"
  },
  {
    "num_code": "428",
    "alpha_2_code": "LV",
    "alpha_3_code": "LVA",
    "en_short_name": "Latvia",
    "nationality": "Latvian",
    "dial_code": "+371",
    "ar_name": "لاتفيا"
  },
  {
    "num_code": "422",
    "alpha_2_code": "LB",
    "alpha_3_code": "LBN",
    "en_short_name": "Lebanon",
    "nationality": "Lebanese",
    "dial_code": "+961",
    "ar_name": "لبنان"
  },
  {
    "num_code": "426",
    "alpha_2_code": "LS",
    "alpha_3_code": "LSO",
    "en_short_name": "Lesotho",
    "nationality": "Basotho",
    "dial_code": "+266",
    "ar_name": "ليسوتو"
  },
  {
    "num_code": "430",
    "alpha_2_code": "LR",
    "alpha_3_code": "LBR",
    "en_short_name": "Liberia",
    "nationality": "Liberian",
    "dial_code": "+231",
    "ar_name": "ليبيريا"
  },
  {
    "num_code": "434",
    "alpha_2_code": "LY",
    "alpha_3_code": "LBY",
    "en_short_name": "Libya",
    "nationality": "Libyan",
    "dial_code": "+218",
    "ar_name": "ليبيا"
  },
  {
    "num_code": "438",
    "alpha_2_code": "LI",
    "alpha_3_code": "LIE",
    "en_short_name": "Liechtenstein",
    "nationality": "Liechtenstein",
    "dial_code": "+423",
    "ar_name": "ليختنشتاين"
  },
  {
    "num_code": "440",
    "alpha_2_code": "LT",
    "alpha_3_code": "LTU",
    "en_short_name": "Lithuania",
    "nationality": "Lithuanian",
    "dial_code": "+370",
    "ar_name": "ليتوانيا"
  },
  {
    "num_code": "442",
    "alpha_2_code": "LU",
    "alpha_3_code": "LUX",
    "en_short_name": "Luxembourg",
    "nationality": "Luxembourg, Luxembourgish",
    "dial_code": "+352",
    "ar_name": "لوكسمبورغ"
  },
  {
    "num_code": "446",
    "alpha_2_code": "MO",
    "alpha_3_code": "MAC",
    "en_short_name": "Macao",
    "nationality": "Macanese, Chinese",
    "dial_code": "+853",
    "ar_name": "ماكاو"
  },
  {
    "num_code": "807",
    "alpha_2_code": "MK",
    "alpha_3_code": "MKD",
    "en_short_name": "Macedonia (the former Yugoslav Republic of)",
    "nationality": "Macedonian",
    "dial_code": "+389",
    "ar_name": "مقدونيا الشمالية"
  },
  {
    "num_code": "450",
    "alpha_2_code": "MG",
    "alpha_3_code": "MDG",
    "en_short_name": "Madagascar",
    "nationality": "Malagasy",
    "dial_code": "+261",
    "ar_name": "مدغشقر"
  },
  {
    "num_code": "454",
    "alpha_2_code": "MW",
    "alpha_3_code": "MWI",
    "en_short_name": "Malawi",
    "nationality": "Malawian",
    "dial_code": "+265",
    "ar_name": "مالاوي"
  },
  {
    "num_code": "458",
    "alpha_2_code": "MY",
    "alpha_3_code": "MYS",
    "en_short_name": "Malaysia",
    "nationality": "Malaysian",
    "dial_code": "+60",
    "ar_name": "ماليزيا"
  },
  {
    "num_code": "462",
    "alpha_2_code": "MV",
    "alpha_3_code": "MDV",
    "en_short_name": "Maldives",
    "nationality": "Maldivian",
    "dial_code": "+960",
    "ar_name": "جزر المالديف"
  },
  {
    "num_code": "466",
    "alpha_2_code": "ML",
    "alpha_3_code": "MLI",
    "en_short_name": "Mali",
    "nationality": "Malian, Malinese",
    "dial_code": "+223",
    "ar_name": "مالي"
  },
  {
    "num_code": "470",
    "alpha_2_code": "MT",
    "alpha_3_code": "MLT",
    "en_short_name": "Malta",
    "nationality": "Maltese",
    "dial_code": "+356",
    "ar_name": "مالطا"
  },
  {
    "num_code": "584",
    "alpha_2_code": "MH",
    "alpha_3_code": "MHL",
    "en_short_name": "Marshall Islands",
    "nationality": "Marshallese",
    "dial_code": "+692",
    "ar_name": "جزر مارشال"
  },
  {
    "num_code": "474",
    "alpha_2_code": "MQ",
    "alpha_3_code": "MTQ",
    "en_short_name": "Martinique",
    "nationality": "Martiniquais, Martinican",
    "dial_code": "+596",
    "ar_name": "مارتينيك"
  },
  {
    "num_code": "478",
    "alpha_2_code": "MR",
    "alpha_3_code": "MRT",
    "en_short_name": "Mauritania",
    "nationality": "Mauritanian",
    "dial_code": "+222",
    "ar_name": "موريتانيا"
  },
  {
    "num_code": "480",
    "alpha_2_code": "MU",
    "alpha_3_code": "MUS",
    "en_short_name": "Mauritius",
    "nationality": "Mauritian",
    "dial_code": "+230",
    "ar_name": "موريشيوس"
  },
  {
    "num_code": "175",
    "alpha_2_code": "YT",
    "alpha_3_code": "MYT",
    "en_short_name": "Mayotte",
    "nationality": "Mahoran",
    "dial_code": "+262",
    "ar_name": "مايوت"
  },
  {
    "num_code": "484",
    "alpha_2_code": "MX",
    "alpha_3_code": "MEX",
    "en_short_name": "Mexico",
    "nationality": "Mexican",
    "dial_code": "+52",
    "ar_name": "المكسيك"
  },
  {
    "num_code": "583",
    "alpha_2_code": "FM",
    "alpha_3_code": "FSM",
    "en_short_name": "Micronesia (Federated States of)",
    "nationality": "Micronesian",
    "dial_code": "+691",
    "ar_name": "ولايات ميكرونيسيا المتحدة"
  },
  {
    "num_code": "498",
    "alpha_2_code": "MD",
    "alpha_3_code": "MDA",
    "en_short_name": "Moldova (Republic of)",
    "nationality": "Moldovan",
    "dial_code": "+373",
    "ar_name": "مولدوفا"
  },
  {
    "num_code": "492",
    "alpha_2_code": "MC",
    "alpha_3_code": "MCO",
    "en_short_name": "Monaco",
    "nationality": "Monégasque, Monacan",
    "dial_code": "+377",
    "ar_name": "موناكو"
  },
  {
    "num_code": "496",
    "alpha_2_code": "MN",
    "alpha_3_code": "MNG",
    "en_short_name": "Mongolia",
    "nationality": "Mongolian",
    "dial_code": "+976",
    "ar_name": "منغوليا"
  },
  {
    "num_code": "499",
    "alpha_2_code": "ME",
    "alpha_3_code": "MNE",
    "en_short_name": "Montenegro",
    "nationality": "Montenegrin",
    "dial_code": "+382",
    "ar_name": "الجبل الأسود"
  },
  {
    "num_code": "500",
    "alpha_2_code": "MS",
    "alpha_3_code": "MSR",
    "en_short_name": "Montserrat",
    "nationality": "Montserratian",
    "dial_code": "+1664",
    "ar_name": "مونتسرات"
  },
  {
    "num_code": "504",
    "alpha_2_code": "MA",
    "alpha_3_code": "MAR",
    "en_short_name": "Morocco",
    "nationality": "Moroccan",
    "dial_code": "+212",
    "ar_name": "المغرب"
  },
  {
    "num_code": "508",
    "alpha_2_code": "MZ",
    "alpha_3_code": "MOZ",
    "en_short_name": "Mozambique",
    "nationality": "Mozambican",
    "dial_code": "+258",
    "ar_name": "موزمبيق"
  },
  {
    "num_code": "104",
    "alpha_2_code": "MM",
    "alpha_3_code": "MMR",
    "en_short_name": "Myanmar",
    "nationality": "Burmese",
    "dial_code": "+95",
    "ar_name": "بورما"
  },
  {
    "num_code": "516",
    "alpha_2_code": "NA",
    "alpha_3_code": "NAM",
    "en_short_name": "Namibia",
    "nationality": "Namibian",
    "dial_code": "+264",
    "ar_name": "ناميبيا"
  },
  {
    "num_code": "520",
    "alpha_2_code": "NR",
    "alpha_3_code": "NRU",
    "en_short_name": "Nauru",
    "nationality": "Nauruan",
    "dial_code": "+674",
    "ar_name": "ناورو"
  },
  {
    "num_code": "524",
    "alpha_2_code": "NP",
    "alpha_3_code": "NPL",
    "en_short_name": "Nepal",
    "nationality": "Nepali, Nepalese",
    "dial_code": "+977",
    "ar_name": "نيبال"
  },
  {
    "num_code": "528",
    "alpha_2_code": "NL",
    "alpha_3_code": "NLD",
    "en_short_name": "Netherlands",
    "nationality": "Dutch, Netherlandic",
    "dial_code": "+31",
    "ar_name": "هولندا"
  },
  {
    "num_code": "540",
    "alpha_2_code": "NC",
    "alpha_3_code": "NCL",
    "en_short_name": "New Caledonia",
    "nationality": "New Caledonian",
    "dial_code": "+687",
    "ar_name": "كاليدونيا الجديدة"
  },
  {
    "num_code": "554",
    "alpha_2_code": "NZ",
    "alpha_3_code": "NZL",
    "en_short_name": "New Zealand",
    "nationality": "New Zealand, NZ",
    "dial_code": "+64",
    "ar_name": "نيوزيلندا"
  },
  {
    "num_code": "558",
    "alpha_2_code": "NI",
    "alpha_3_code": "NIC",
    "en_short_name": "Nicaragua",
    "nationality": "Nicaraguan",
    "dial_code": "+505",
    "ar_name": "نيكاراغوا"
  },
  {
    "num_code": "562",
    "alpha_2_code": "NE",
    "alpha_3_code": "NER",
    "en_short_name": "Niger",
    "nationality": "Nigerien",
    "dial_code": "+227",
    "ar_name": "النيجر"
  },
  {
    "num_code": "566",
    "alpha_2_code": "NG",
    "alpha_3_code": "NGA",
    "en_short_name": "Nigeria",
    "nationality": "Nigerian",
    "dial_code": "+234",
    "ar_name": "نيجيريا"
  },
  {
    "num_code": "570",
    "alpha_2_code": "NU",
    "alpha_3_code": "NIU",
    "en_short_name": "Niue",
    "nationality": "Niuean",
    "dial_code": "+683",
    "ar_name": "نييوي"
  },
  {
    "num_code": "574",
    "alpha_2_code": "NF",
    "alpha_3_code": "NFK",
    "en_short_name": "Norfolk Island",
    "nationality": "Norfolk Island",
    "dial_code": "+672",
    "ar_name": "جزيرة نورفولك"
  },
  {
    "num_code": "580",
    "alpha_2_code": "MP",
    "alpha_3_code": "MNP",
    "en_short_name": "Northern Mariana Islands",
    "nationality": "Northern Marianan",
    "dial_code": "+1670",
    "ar_name": "جزر ماريانا الشمالية"
  },
  {
    "num_code": "578",
    "alpha_2_code": "NO",
    "alpha_3_code": "NOR",
    "en_short_name": "Norway",
    "nationality": "Norwegian",
    "dial_code": "+47",
    "ar_name": "النرويج"
  },
  {
    "num_code": "512",
    "alpha_2_code": "OM",
    "alpha_3_code": "OMN",
    "en_short_name": "Oman",
    "nationality": "Omani",
    "dial_code": "+968",
    "ar_name": "عمان"
  },
  {
    "num_code": "586",
    "alpha_2_code": "PK",
    "alpha_3_code": "PAK",
    "en_short_name": "Pakistan",
    "nationality": "Pakistani",
    "dial_code": "+92",
    "ar_name": "باكستان"
  },
  {
    "num_code": "585",
    "alpha_2_code": "PW",
    "alpha_3_code": "PLW",
    "en_short_name": "Palau",
    "nationality": "Palauan",
    "dial_code": "+680",
    "ar_name": "بالاو"
  },
  {
    "num_code": "275",
    "alpha_2_code": "PS",
    "alpha_3_code": "PSE",
    "en_short_name": "Palestine, State of",
    "nationality": "Palestinian",
    "dial_code": "+970",
    "ar_name": "فلسطين"
  },
  {
    "num_code": "591",
    "alpha_2_code": "PA",
    "alpha_3_code": "PAN",
    "en_short_name": "Panama",
    "nationality": "Panamanian",
    "dial_code": "+507",
    "ar_name": "بنما"
  },
  {
    "num_code": "598",
    "alpha_2_code": "PG",
    "alpha_3_code": "PNG",
    "en_short_name": "Papua New Guinea",
    "nationality": "Papua New Guinean, Papuan",
    "dial_code": "+675",
    "ar_name": "بابوا غينيا الجديدة"
  },
  {
    "num_code": "600",
    "alpha_2_code": "PY",
    "alpha_3_code": "PRY",
    "en_short_name": "Paraguay",
    "nationality": "Paraguayan",
    "dial_code": "+595",
    "ar_name": "باراغواي"
  },
  {
    "num_code": "604",
    "alpha_2_code": "PE",
    "alpha_3_code": "PER",
    "en_short_name": "Peru",
    "nationality": "Peruvian",
    "dial_code": "+51",
    "ar_name": "بيرو"
  },
  {
    "num_code": "608",
    "alpha_2_code": "PH",
    "alpha_3_code": "PHL",
    "en_short_name": "Philippines",
    "nationality": "Philippine, Filipino",
    "dial_code": "+63",
    "ar_name": "الفلبين"
  },
  {
    "num_code": "612",
    "alpha_2_code": "PN",
    "alpha_3_code": "PCN",
    "en_short_name": "Pitcairn",
    "nationality": "Pitcairn Island",
    "dial_code": "+64",
    "ar_name": "جزر بيتكيرن"
  },
  {
    "num_code": "616",
    "alpha_2_code": "PL",
    "alpha_3_code": "POL",
    "en_short_name": "Poland",
    "nationality": "Polish",
    "dial_code": "+48",
    "ar_name": "بولندا"
  },
  {
    "num_code": "620",
    "alpha_2_code": "PT",
    "alpha_3_code": "PRT",
    "en_short_name": "Portugal",
    "nationality": "Portuguese",
    "dial_code": "+351",
    "ar_name": "البرتغال"
  },
  {
    "num_code": "630",
    "alpha_2_code": "PR",
    "alpha_3_code": "PRI",
    "en_short_name": "Puerto Rico",
    "nationality": "Puerto Rican",
    "dial_code": "+1939",
    "ar_name": "بورتوريكو"
  },
  {
    "num_code": "634",
    "alpha_2_code": "QA",
    "alpha_3_code": "QAT",
    "en_short_name": "Qatar",
    "nationality": "Qatari",
    "dial_code": "+974",
    "ar_name": "قطر"
  },
  {
    "num_code": "638",
    "alpha_2_code": "RE",
    "alpha_3_code": "REU",
    "en_short_name": "Réunion",
    "nationality": "Réunionese, Réunionnais",
    "dial_code": "+262",
    "ar_name": "لا ريونيون"
  },
  {
    "num_code": "642",
    "alpha_2_code": "RO",
    "alpha_3_code": "ROU",
    "en_short_name": "Romania",
    "nationality": "Romanian",
    "dial_code": "+40",
    "ar_name": "رومانيا"
  },
  {
    "num_code": "643",
    "alpha_2_code": "RU",
    "alpha_3_code": "RUS",
    "en_short_name": "Russian Federation",
    "nationality": "Russian",
    "dial_code": "+7",
    "ar_name": "روسيا"
  },
  {
    "num_code": "646",
    "alpha_2_code": "RW",
    "alpha_3_code": "RWA",
    "en_short_name": "Rwanda",
    "nationality": "Rwandan",
    "dial_code": "+250",
    "ar_name": "رواندا"
  },
  {
    "num_code": "652",
    "alpha_2_code": "BL",
    "alpha_3_code": "BLM",
    "en_short_name": "Saint Barthélemy",
    "nationality": "Barthélemois",
    "dial_code": "+590",
    "ar_name": "سان بارتيلمي"
  },
  {
    "num_code": "654",
    "alpha_2_code": "SH",
    "alpha_3_code": "SHN",
    "en_short_name": "Saint Helena, Ascension and Tristan da Cunha",
    "nationality": "Saint Helenian",
    "dial_code": "+290",
    "ar_name": "سانت هيلينا وأسينشين وتريستان دا كونا"
  },
  {
    "num_code": "659",
    "alpha_2_code": "KN",
    "alpha_3_code": "KNA",
    "en_short_name": "Saint Kitts and Nevis",
    "nationality": "Kittitian or Nevisian",
    "dial_code": "+1869",
    "ar_name": "سانت كيتس ونيفيس"
  },
  {
    "num_code": "662",
    "alpha_2_code": "LC",
    "alpha_3_code": "LCA",
    "en_short_name": "Saint Lucia",
    "nationality": "Saint Lucian",
    "dial_code": "+1758",
    "ar_name": "سانت لوسيا"
  },
  {
    "num_code": "663",
    "alpha_2_code": "MF",
    "alpha_3_code": "MAF",
    "en_short_name": "Saint Martin (French part)",
    "nationality": "Saint-Martinoise",
    "dial_code": "+590",
    "ar_name": "سانت مارتن (الجزء الفرنسي)"
  },
  {
    "num_code": "666",
    "alpha_2_code": "PM",
    "alpha_3_code": "SPM",
    "en_short_name": "Saint Pierre and Miquelon",
    "nationality": "Saint-Pierrais or Miquelonnais",
    "dial_code": "+508",
    "ar_name": "سان بيير وميكلون"
  },
  {
    "num_code": "670",
    "alpha_2_code": "VC",
    "alpha_3_code": "VCT",
    "en_short_name": "Saint Vincent and the Grenadines",
    "nationality": "Saint Vincentian, Vincentian",
    "dial_code": "+1784",
    "ar_name": "سانت فينسنت والغرينادين"
  },
  {
    "num_code": "882",
    "alpha_2_code": "WS",
    "alpha_3_code": "WSM",
    "en_short_name": "Samoa",
    "nationality": "Samoan",
    "dial_code": "+685",
    "ar_name": "ساموا"
  },
  {
    "num_code": "674",
    "alpha_2_code": "SM",
    "alpha_3_code": "SMR",
    "en_short_name": "San Marino",
    "nationality": "Sammarinese",
    "dial_code": "+378",
    "ar_name": "سان مارينو"
  },
  {
    "num_code": "678",
    "alpha_2_code": "ST",
    "alpha_3_code": "STP",
    "en_short_name": "Sao Tome and Principe",
    "nationality": "São Toméan",
    "dial_code": "+239",
    "ar_name": "ساو تومي وبرينسيب"
  },
  {
    "num_code": "686",
    "alpha_2_code": "SN",
    "alpha_3_code": "SEN",
    "en_short_name": "Senegal",
    "nationality": "Senegalese",
    "dial_code": "+221",
    "ar_name": "السنغال"
  },
  {
    "num_code": "688",
    "alpha_2_code": "RS",
    "alpha_3_code": "SRB",
    "en_short_name": "Serbia",
    "nationality": "Serbian",
    "dial_code": "+381",
    "ar_name": "صربيا"
  },
  {
    "num_code": "690",
    "alpha_2_code": "SC",
    "alpha_3_code": "SYC",
    "en_short_name": "Seychelles",
    "nationality": "Seychellois",
    "dial_code": "+248",
    "ar_name": "سيشل"
  },
  {
    "num_code": "694",
    "alpha_2_code": "SL",
    "alpha_3_code": "SLE",
    "en_short_name": "Sierra Leone",
    "nationality": "Sierra Leonean",
    "dial_code": "+232",
    "ar_name": "سيراليون"
  },
  {
    "num_code": "702",
    "alpha_2_code": "SG",
    "alpha_3_code": "SGP",
    "en_short_name": "Singapore",
    "nationality": "Singaporean",
    "dial_code": "+65",
    "ar_name": "سنغافورة"
  },
  {
    "num_code": "703",
    "alpha_2_code": "SK",
    "alpha_3_code": "SVK",
    "en_short_name": "Slovakia",
    "nationality": "Slovak",
    "dial_code": "+421",
    "ar_name": "سلوفاكيا"
  },
  {
    "num_code": "705",
    "alpha_2_code": "SI",
    "alpha_3_code": "SVN",
    "en_short_name": "Slovenia",
    "nationality": "Slovenian, Slovene",
    "dial_code": "+386",
    "ar_name": "سلوفينيا"
  },
  {
    "num_code": "90",
    "alpha_2_code": "SB",
    "alpha_3_code": "SLB",
    "en_short_name": "Solomon Islands",
    "nationality": "Solomon Island",
    "dial_code": "+677",
    "ar_name": "جزر سليمان"
  },
  {
    "num_code": "706",
    "alpha_2_code": "SO",
    "alpha_3_code": "SOM",
    "en_short_name": "Somalia",
    "nationality": "Somali, Somalian",
    "dial_code": "+252",
    "ar_name": "الصومال"
  },
  {
    "num_code": "710",
    "alpha_2_code": "ZA",
    "alpha_3_code": "ZAF",
    "en_short_name": "South Africa",
    "nationality": "South African",
    "dial_code": "+27",
    "ar_name": "جنوب أفريقيا"
  },
  {
    "num_code": "239",
    "alpha_2_code": "GS",
    "alpha_3_code": "SGS",
    "en_short_name": "South Georgia and the South Sandwich Islands",
    "nationality": "South Georgia or South Sandwich Islands",
    "dial_code": "+500",
    "ar_name": "جورجيا الجنوبية وجزر ساندويتش الجنوبية"
  },
  {
    "num_code": "728",
    "alpha_2_code": "SS",
    "alpha_3_code": "SSD",
    "en_short_name": "South Sudan",
    "nationality": "South Sudanese",
    "dial_code": "+211",
    "ar_name": "جنوب السودان"
  },
  {
    "num_code": "724",
    "alpha_2_code": "ES",
    "alpha_3_code": "ESP",
    "en_short_name": "Spain",
    "nationality": "Spanish",
    "dial_code": "+34",
    "ar_name": "إسبانيا"
  },
  {
    "num_code": "144",
    "alpha_2_code": "LK",
    "alpha_3_code": "LKA",
    "en_short_name": "Sri Lanka",
    "nationality": "Sri Lankan",
    "dial_code": "+94",
    "ar_name": "سريلانكا"
  },
  {
    "num_code": "729",
    "alpha_2_code": "SD",
    "alpha_3_code": "SDN",
    "en_short_name": "Sudan",
    "nationality": "Sudanese",
    "dial_code": "+249",
    "ar_name": "السودان"
  },
  {
    "num_code": "740",
    "alpha_2_code": "SR",
    "alpha_3_code": "SUR",
    "en_short_name": "Suriname",
    "nationality": "Surinamese",
    "dial_code": "+597",
    "ar_name": "سورينام"
  },
  {
    "num_code": "744",
    "alpha_2_code": "SJ",
    "alpha_3_code": "SJM",
    "en_short_name": "Svalbard and Jan Mayen",
    "nationality": "Svalbard",
    "dial_code": "+47",
    "ar_name": "سفالبارد ويان ماين"
  },
  {
    "num_code": "748",
    "alpha_2_code": "SZ",
    "alpha_3_code": "SWZ",
    "en_short_name": "Swaziland",
    "nationality": "Swazi",
    "dial_code": "+268",
    "ar_name": "سوازيلاند"
  },
  {
    "num_code": "752",
    "alpha_2_code": "SE",
    "alpha_3_code": "SWE",
    "en_short_name": "Sweden",
    "nationality": "Swedish",
    "dial_code": "+46",
    "ar_name": "السويد"
  },
  {
    "num_code": "756",
    "alpha_2_code": "CH",
    "alpha_3_code": "CHE",
    "en_short_name": "Switzerland",
    "nationality": "Swiss",
    "dial_code": "+41",
    "ar_name": "سويسرا"
  },
  {
    "num_code": "760",
    "alpha_2_code": "SY",
    "alpha_3_code": "SYR",
    "en_short_name": "Syrian Arab Republic",
    "nationality": "Syrian",
    "dial_code": "+963",
    "ar_name": "سوريا"
  },
  {
    "num_code": "158",
    "alpha_2_code": "TW",
    "alpha_3_code": "TWN",
    "en_short_name": "Taiwan, Province of China",
    "nationality": "Chinese, Taiwanese",
    "dial_code": "+886",
    "ar_name": "تايوان"
  },
  {
    "num_code": "762",
    "alpha_2_code": "TJ",
    "alpha_3_code": "TJK",
    "en_short_name": "Tajikistan",
    "nationality": "Tajikistani",
    "dial_code": "+992",
    "ar_name": "طاجيكستان"
  },
  {
    "num_code": "834",
    "alpha_2_code": "TZ",
    "alpha_3_code": "TZA",
    "en_short_name": "Tanzania, United Republic of",
    "nationality": "Tanzanian",
    "dial_code": "+255",
    "ar_name": "تانزانيا"
  },
  {
    "num_code": "764",
    "alpha_2_code": "TH",
    "alpha_3_code": "THA",
    "en_short_name": "Thailand",
    "nationality": "Thai",
    "dial_code": "+66",
    "ar_name": "تايلاند"
  },
  {
    "num_code": "626",
    "alpha_2_code": "TL",
    "alpha_3_code": "TLS",
    "en_short_name": "Timor-Leste",
    "nationality": "Timorese",
    "dial_code": "+670",
    "ar_name": "تيمور الشرقية"
  },
  {
    "num_code": "768",
    "alpha_2_code": "TG",
    "alpha_3_code": "TGO",
    "en_short_name": "Togo",
    "nationality": "Togolese",
    "dial_code": "+228",
    "ar_name": "توغو"
  },
  {
    "num_code": "772",
    "alpha_2_code": "TK",
    "alpha_3_code": "TKL",
    "en_short_name": "Tokelau",
    "nationality": "Tokelauan",
    "dial_code": "+690",
    "ar_name": "توكيلاو"
  },
  {
    "num_code": "776",
    "alpha_2_code": "TO",
    "alpha_3_code": "TON",
    "en_short_name": "Tonga",
    "nationality": "Tongan",
    "dial_code": "+676",
    "ar_name": "تونغا"
  },
  {
    "num_code": "780",
    "alpha_2_code": "TT",
    "alpha_3_code": "TTO",
    "en_short_name": "Trinidad and Tobago",
    "nationality": "Trinidadian or Tobagonian",
    "dial_code": "+1868",
    "ar_name": "ترينيداد وتوباغو"
  },
  {
    "num_code": "788",
    "alpha_2_code": "TN",
    "alpha_3_code": "TUN",
    "en_short_name": "Tunisia",
    "nationality": "Tunisian",
    "dial_code": "+216",
    "ar_name": "تونس"
  },
  {
    "num_code": "792",
    "alpha_2_code": "TR",
    "alpha_3_code": "TUR",
    "en_short_name": "Turkey",
    "nationality": "Turkish",
    "dial_code": "+90",
    "ar_name": "تركيا"
  },
  {
    "num_code": "795",
    "alpha_2_code": "TM",
    "alpha_3_code": "TKM",
    "en_short_name": "Turkmenistan",
    "nationality": "Turkmen",
    "dial_code": "+993",
    "ar_name": "تركمانستان"
  },
  {
    "num_code": "796",
    "alpha_2_code": "TC",
    "alpha_3_code": "TCA",
    "en_short_name": "Turks and Caicos Islands",
    "nationality": "Turks and Caicos Island",
    "dial_code": "+1649",
    "ar_name": "جزر توركس وكايكوس"
  },
  {
    "num_code": "798",
    "alpha_2_code": "TV",
    "alpha_3_code": "TUV",
    "en_short_name": "Tuvalu",
    "nationality": "Tuvaluan",
    "dial_code": "+688",
    "ar_name": "توفالو"
  },
  {
    "num_code": "800",
    "alpha_2_code": "UG",
    "alpha_3_code": "UGA",
    "en_short_name": "Uganda",
    "nationality": "Ugandan",
    "dial_code": "+256",
    "ar_name": "أوغندا"
  },
  {
    "num_code": "804",
    "alpha_2_code": "UA",
    "alpha_3_code": "UKR",
    "en_short_name": "Ukraine",
    "nationality": "Ukrainian",
    "dial_code": "+380",
    "ar_name": "أوكرانيا"
  },
  {
    "num_code": "784",
    "alpha_2_code": "AE",
    "alpha_3_code": "ARE",
    "en_short_name": "United Arab Emirates",
    "nationality": "Emirati, Emirian, Emiri",
    "dial_code": "+971",
    "ar_name": "الإمارات العربية المتحدة"
  },
  {
    "num_code": "826",
    "alpha_2_code": "GB",
    "alpha_3_code": "GBR",
    "en_short_name": "United Kingdom of Great Britain and Northern Ireland",
    "nationality": "British, UK",
    "dial_code": "+44",
    "ar_name": "المملكة المتحدة"
  },
  {
    "num_code": "840",
    "alpha_2_code": "US",
    "alpha_3_code": "USA",
    "en_short_name": "United States of America",
    "nationality": "American",
    "dial_code": "+1",
    "ar_name": "الولايات المتحدة"
  },
  {
    "num_code": "858",
    "alpha_2_code": "UY",
    "alpha_3_code": "URY",
    "en_short_name": "Uruguay",
    "nationality": "Uruguayan",
    "dial_code": "+598",
    "ar_name": "الأوروغواي"
  },
  {
    "num_code": "860",
    "alpha_2_code": "UZ",
    "alpha_3_code": "UZB",
    "en_short_name": "Uzbekistan",
    "nationality": "Uzbekistani, Uzbek",
    "dial_code": "+998",
    "ar_name": "أوزبكستان"
  },
  {
    "num_code": "548",
    "alpha_2_code": "VU",
    "alpha_3_code": "VUT",
    "en_short_name": "Vanuatu",
    "nationality": "Ni-Vanuatu, Vanuatuan",
    "dial_code": "+678",
    "ar_name": "فانواتو"
  },
  {
    "num_code": "862",
    "alpha_2_code": "VE",
    "alpha_3_code": "VEN",
    "en_short_name": "Venezuela (Bolivarian Republic of)",
    "nationality": "Venezuelan",
    "dial_code": "+58",
    "ar_name": "فنزويلا"
  },
  {
    "num_code": "704",
    "alpha_2_code": "VN",
    "alpha_3_code": "VNM",
    "en_short_name": "Vietnam",
    "nationality": "Vietnamese",
    "dial_code": "+84",
    "ar_name": "فيتنام"
  },
  {
    "num_code": "92",
    "alpha_2_code": "VG",
    "alpha_3_code": "VGB",
    "en_short_name": "Virgin Islands (British)",
    "nationality": "British Virgin Island",
    "dial_code": "+1284",
    "ar_name": "جزر العذراء البريطانية"
  },
  {
    "num_code": "850",
    "alpha_2_code": "VI",
    "alpha_3_code": "VIR",
    "en_short_name": "Virgin Islands (U.S.)",
    "nationality": "U.S. Virgin Island",
    "dial_code": "+1340",
    "ar_name": "جزر العذراء الأمريكية"
  },
  {
    "num_code": "876",
    "alpha_2_code": "WF",
    "alpha_3_code": "WLF",
    "en_short_name": "Wallis and Futuna",
    "nationality": "Wallis and Futuna, Wallisian or Futunan",
    "dial_code": "+681",
    "ar_name": "والس وفوتونا"
  },
  {
    "num_code": "887",
    "alpha_2_code": "YE",
    "alpha_3_code": "YEM",
    "en_short_name": "Yemen",
    "nationality": "Yemeni",
    "dial_code": "+967",
    "ar_name": "اليمن"
  },
  {
    "num_code": "894",
    "alpha_2_code": "ZM",
    "alpha_3_code": "ZMB",
    "en_short_name": "Zambia",
    "nationality": "Zambian",
    "dial_code": "+260",
    "ar_name": "زامبيا"
  },
  {
    "num_code": "716",
    "alpha_2_code": "ZW",
    "alpha_3_code": "ZWE",
    "en_short_name": "Zimbabwe",
    "nationality": "Zimbabwean",
    "dial_code": "+263",
    "ar_name": "زيمبابوي"
  }
];
const Map<String, String> countryDialCodes = {
  "SA": "+966",
  "AF": "+93",
  "AX": "+358",
  "AL": "+355",
  "DZ": "+213",
  "AS": "+1684",
  "AD": "+376",
  "AO": "+244",
  "AI": "+1264",
  "AQ": "+672",
  "AG": "+1268",
  "AR": "+54",
  "AM": "+374",
  "AW": "+297",
  "AU": "+61",
  "AT": "+43",
  "AZ": "+994",
  "BS": "+1242",
  "BH": "+973",
  "BD": "+880",
  "BB": "+1246",
  "BY": "+375",
  "BE": "+32",
  "BZ": "+501",
  "BJ": "+229",
  "BM": "+1441",
  "BT": "+975",
  "BO": "+591",
  "BA": "+387",
  "BW": "+267",
  "BV": "+47",
  "BR": "+55",
  "IO": "+246",
  "BN": "+673",
  "BG": "+359",
  "BF": "+226",
  "BI": "+257",
  "CV": "+238",
  "KH": "+855",
  "CM": "+237",
  "CA": "+1",
  "KY": "+ 345",
  "CF": "+236",
  "TD": "+235",
  "CL": "+56",
  "CN": "+86",
  "CX": "+61",
  "CC": "+61",
  "CO": "+57",
  "KM": "+269",
  "CG": "+242",
  "CD": "+243",
  "CK": "+682",
  "CR": "+506",
  "CI": "+225",
  "HR": "+385",
  "CU": "+53",
  "CY": "+357",
  "CZ": "+420",
  "DK": "+45",
  "DJ": "+253",
  "DM": "+1767",
  "DO": "+1849",
  "EC": "+593",
  "EG": "+20",
  "SV": "+503",
  "GQ": "+240",
  "ER": "+291",
  "EE": "+372",
  "ET": "+251",
  "FK": "+500",
  "FO": "+298",
  "FJ": "+679",
  "FI": "+358",
  "FR": "+33",
  "GF": "+594",
  "PF": "+689",
  "TF": "+262",
  "GA": "+241",
  "GM": "+220",
  "GE": "+995",
  "DE": "+49",
  "GH": "+233",
  "GI": "+350",
  "GR": "+30",
  "GL": "+299",
  "GD": "+1473",
  "GP": "+590",
  "GU": "+1671",
  "GT": "+502",
  "GG": "+44",
  "GN": "+224",
  "GW": "+245",
  "GY": "+592",
  "HT": "+509",
  "HM": "+0",
  "VA": "+379",
  "HN": "+504",
  "HK": "+852",
  "HU": "+36",
  "IS": "+354",
  "IN": "+91",
  "ID": "+62",
  "IR": "+98",
  "IQ": "+964",
  "IE": "+353",
  "IM": "+44",
  "IT": "+39",
  "JM": "+1876",
  "JP": "+81",
  "JE": "+44",
  "JO": "+962",
  "KZ": "+7",
  "KE": "+254",
  "KI": "+686",
  "KP": "+850",
  "KR": "+82",
  "KW": "+965",
  "KG": "+996",
  "LA": "+856",
  "LV": "+371",
  "LB": "+961",
  "LS": "+266",
  "LR": "+231",
  "LY": "+218",
  "LI": "+423",
  "LT": "+370",
  "LU": "+352",
  "MO": "+853",
  "MK": "+389",
  "MG": "+261",
  "MW": "+265",
  "MY": "+60",
  "MV": "+960",
  "ML": "+223",
  "MT": "+356",
  "MH": "+692",
  "MQ": "+596",
  "MR": "+222",
  "MU": "+230",
  "YT": "+262",
  "MX": "+52",
  "FM": "+691",
  "MD": "+373",
  "MC": "+377",
  "MN": "+976",
  "ME": "+382",
  "MS": "+1664",
  "MA": "+212",
  "MZ": "+258",
  "MM": "+95",
  "NA": "+264",
  "NR": "+674",
  "NP": "+977",
  "NL": "+31",
  "NC": "+687",
  "NZ": "+64",
  "NI": "+505",
  "NE": "+227",
  "NG": "+234",
  "NU": "+683",
  "NF": "+672",
  "MP": "+1670",
  "NO": "+47",
  "OM": "+968",
  "PK": "+92",
  "PW": "+680",
  "PS": "+970",
  "PA": "+507",
  "PG": "+675",
  "PY": "+595",
  "PE": "+51",
  "PH": "+63",
  "PN": "+64",
  "PL": "+48",
  "PT": "+351",
  "PR": "+1939",
  "QA": "+974",
  "RE": "+262",
  "RO": "+40",
  "RU": "+7",
  "RW": "+250",
  "BL": "+590",
  "SH": "+290",
  "KN": "+1869",
  "LC": "+1758",
  "MF": "+590",
  "PM": "+508",
  "VC": "+1784",
  "WS": "+685",
  "SM": "+378",
  "ST": "+239",
  "SN": "+221",
  "RS": "+381",
  "SC": "+248",
  "SL": "+232",
  "SG": "+65",
  "SK": "+421",
  "SI": "+386",
  "SB": "+677",
  "SO": "+252",
  "ZA": "+27",
  "GS": "+500",
  "SS": "+211",
  "ES": "+34",
  "LK": "+94",
  "SD": "+249",
  "SR": "+597",
  "SJ": "+47",
  "SZ": "+268",
  "SE": "+46",
  "CH": "+41",
  "SY": "+963",
  "TW": "+886",
  "TJ": "+992",
  "TZ": "+255",
  "TH": "+66",
  "TL": "+670",
  "TG": "+228",
  "TK": "+690",
  "TO": "+676",
  "TT": "+1868",
  "TN": "+216",
  "TR": "+90",
  "TM": "+993",
  "TC": "+1649",
  "TV": "+688",
  "UG": "+256",
  "UA": "+380",
  "AE": "+971",
  "GB": "+44",
  "US": "+1",
  "UY": "+598",
  "UZ": "+998",
  "VU": "+678",
  "VE": "+58",
  "VN": "+84",
  "VG": "+1284",
  "VI": "+1340",
  "WF": "+681",
  "YE": "+967",
  "ZM": "+260",
  "ZW": "+263"
};
const Map<String, Map<String, dynamic>> countryPhoneRules = {
  "SA": {"code": "966", "num_code": "682", "minLength": 9, "maxLength": 12},
  "AF": {"code": "93", "num_code": "4", "minLength": 9, "maxLength": 10},
  "AX": {"code": "358", "num_code": "248", "minLength": 7, "maxLength": 12},
  "AL": {"code": "355", "num_code": "8", "minLength": 9, "maxLength": 9},
  "DZ": {"code": "213", "num_code": "12", "minLength": 9, "maxLength": 9},
  "AS": {"code": "1684", "num_code": "16", "minLength": 10, "maxLength": 10},
  "AD": {"code": "376", "num_code": "20", "minLength": 6, "maxLength": 9},
  "AO": {"code": "244", "num_code": "24", "minLength": 9, "maxLength": 9},
  "AI": {"code": "1264", "num_code": "660", "minLength": 10, "maxLength": 10},
  "AQ": {"code": "672", "num_code": "10", "minLength": 6, "maxLength": 6},
  "AG": {"code": "1268", "num_code": "28", "minLength": 10, "maxLength": 10},
  "AR": {"code": "54", "num_code": "32", "minLength": 10, "maxLength": 13},
  "AM": {"code": "374", "num_code": "51", "minLength": 8, "maxLength": 9},
  "AW": {"code": "297", "num_code": "533", "minLength": 7, "maxLength": 7},
  "AU": {"code": "61", "num_code": "36", "minLength": 9, "maxLength": 10},
  "AT": {"code": "43", "num_code": "40", "minLength": 10, "maxLength": 13},
  "AZ": {"code": "994", "num_code": "31", "minLength": 9, "maxLength": 9},
  "BS": {"code": "1242", "num_code": "44", "minLength": 10, "maxLength": 10},
  "BH": {"code": "973", "num_code": "48", "minLength": 8, "maxLength": 8},
  "BD": {"code": "880", "num_code": "50", "minLength": 10, "maxLength": 10},
  "BB": {"code": "1246", "num_code": "52", "minLength": 7, "maxLength": 7},
  "BY": {"code": "375", "num_code": "112", "minLength": 9, "maxLength": 9},
  "BE": {"code": "32", "num_code": "56", "minLength": 9, "maxLength": 9},
  "BZ": {"code": "501", "num_code": "84", "minLength": 7, "maxLength": 7},
  "BJ": {"code": "229", "num_code": "204", "minLength": 8, "maxLength": 8},
  "BM": {"code": "1441", "num_code": "60", "minLength": 10, "maxLength": 10},
  "BT": {"code": "975", "num_code": "64", "minLength": 8, "maxLength": 8},
  "BO": {"code": "591", "num_code": "68", "minLength": 8, "maxLength": 8},
  "BA": {"code": "387", "num_code": "70", "minLength": 8, "maxLength": 8},
  "BW": {"code": "267", "num_code": "72", "minLength": 7, "maxLength": 8},
  "BR": {"code": "55", "num_code": "76", "minLength": 10, "maxLength": 11},
  "IO": {"code": "246", "num_code": "86", "minLength": 7, "maxLength": 7},
  "BN": {"code": "673", "num_code": "96", "minLength": 7, "maxLength": 7},
  "BG": {"code": "359", "num_code": "100", "minLength": 9, "maxLength": 9},
  "BF": {"code": "226", "num_code": "854", "minLength": 8, "maxLength": 8},
  "BI": {"code": "257", "num_code": "108", "minLength": 8, "maxLength": 8},
  "CV": {"code": "238", "num_code": "132", "minLength": 7, "maxLength": 7},
  "KH": {"code": "855", "num_code": "116", "minLength": 9, "maxLength": 9},
  "CM": {"code": "237", "num_code": "120", "minLength": 9, "maxLength": 9},
  "CA": {"code": "1", "num_code": "124", "minLength": 10, "maxLength": 10},
  "CL": {"code": "56", "num_code": "152", "minLength": 9, "maxLength": 9},
  "CN": {"code": "86", "num_code": "156", "minLength": 11, "maxLength": 11},
  "CO": {"code": "57", "num_code": "170", "minLength": 10, "maxLength": 10},
  "CR": {"code": "506", "num_code": "188", "minLength": 8, "maxLength": 8},
  "CI": {"code": "225", "num_code": "384", "minLength": 8, "maxLength": 8},
  "HR": {"code": "385", "num_code": "191", "minLength": 9, "maxLength": 9},
  "CU": {"code": "53", "num_code": "192", "minLength": 8, "maxLength": 8},
  "CY": {"code": "357", "num_code": "196", "minLength": 8, "maxLength": 8},
  "CZ": {"code": "420", "num_code": "203", "minLength": 9, "maxLength": 9},
  "DE": {"code": "49", "num_code": "276", "minLength": 10, "maxLength": 11},
  "GH": {"code": "233", "num_code": "288", "minLength": 9, "maxLength": 10},
  "IN": {"code": "91", "num_code": "356", "minLength": 10, "maxLength": 10},
  "NG": {"code": "234", "num_code": "566", "minLength": 10, "maxLength": 11},
  "PH": {"code": "63", "num_code": "608", "minLength": 10, "maxLength": 10},
  "PK": {"code": "92", "num_code": "586", "minLength": 10, "maxLength": 11},
  "US": {"code": "1", "num_code": "840", "minLength": 10, "maxLength": 10},
  "BV": {"code": "47", "num_code": "74", "minLength": 8, "maxLength": 12},
  "KY": {"code": "345", "num_code": "136", "minLength": 10, "maxLength": 10},
  "CF": {"code": "236", "num_code": "140", "minLength": 8, "maxLength": 11},
  "TD": {"code": "235", "num_code": "148", "minLength": 8, "maxLength": 11},
  "CX": {"code": "61", "num_code": "162", "minLength": 9, "maxLength": 10},
  "CC": {"code": "61", "num_code": "166", "minLength": 9, "maxLength": 10},
  "KM": {"code": "269", "num_code": "174", "minLength": 7, "maxLength": 10},
  "CG": {"code": "242", "num_code": "178", "minLength": 9, "maxLength": 10},
  "CD": {"code": "243", "num_code": "180", "minLength": 9, "maxLength": 10},
  "CK": {"code": "682", "num_code": "184", "minLength": 5, "maxLength": 7},
  "DK": {"code": "45", "num_code": "208", "minLength": 8, "maxLength": 8},
  "DJ": {"code": "253", "num_code": "262", "minLength": 8, "maxLength": 8},
  "DM": {"code": "1767", "num_code": "212", "minLength": 10, "maxLength": 10},
  "DO": {"code": "1849", "num_code": "214", "minLength": 10, "maxLength": 10},
  "EC": {"code": "593", "num_code": "218", "minLength": 9, "maxLength": 9},
  "EG": {"code": "20", "num_code": "818", "minLength": 10, "maxLength": 10},
  "SV": {"code": "503", "num_code": "222", "minLength": 8, "maxLength": 8},
  "GQ": {"code": "240", "num_code": "226", "minLength": 9, "maxLength": 9},
  "ER": {"code": "291", "num_code": "232", "minLength": 7, "maxLength": 9},
  "EE": {"code": "372", "num_code": "233", "minLength": 7, "maxLength": 9},
  "ET": {"code": "251", "num_code": "231", "minLength": 9, "maxLength": 10},
  "FK": {"code": "500", "num_code": "238", "minLength": 5, "maxLength": 5},
  "FO": {"code": "298", "num_code": "234", "minLength": 6, "maxLength": 9},
  "FJ": {"code": "679", "num_code": "242", "minLength": 7, "maxLength": 9},
  "FI": {"code": "358", "num_code": "246", "minLength": 9, "maxLength": 10},
  "FR": {"code": "33", "num_code": "250", "minLength": 9, "maxLength": 10},
  "GF": {"code": "594", "num_code": "254", "minLength": 9, "maxLength": 9},
  "PF": {"code": "689", "num_code": "258", "minLength": 6, "maxLength": 8},
  "TF": {"code": "262", "num_code": "260", "minLength": 9, "maxLength": 9},
  "GA": {"code": "241", "num_code": "266", "minLength": 7, "maxLength": 9},
  "GM": {"code": "220", "num_code": "270", "minLength": 7, "maxLength": 9},
  "GE": {"code": "995", "num_code": "268", "minLength": 9, "maxLength": 9},
  "GI": {"code": "350", "num_code": "292", "minLength": 8, "maxLength": 9},
  "GR": {"code": "30", "num_code": "300", "minLength": 10, "maxLength": 10},
  "GL": {"code": "299", "num_code": "304", "minLength": 6, "maxLength": 9},
  "GD": {"code": "1473", "num_code": "308", "minLength": 10, "maxLength": 10},
  "GP": {"code": "590", "num_code": "312", "minLength": 9, "maxLength": 9},
  "GU": {"code": "1671", "num_code": "316", "minLength": 10, "maxLength": 10},
  "GT": {"code": "502", "num_code": "320", "minLength": 8, "maxLength": 9},
  "GG": {"code": "44", "num_code": "831", "minLength": 10, "maxLength": 10},
  "GN": {"code": "224", "num_code": "324", "minLength": 8, "maxLength": 9},
  "GW": {"code": "245", "num_code": "624", "minLength": 7, "maxLength": 9},
  "GY": {"code": "592", "num_code": "328", "minLength": 7, "maxLength": 9},
  "HT": {"code": "509", "num_code": "332", "minLength": 8, "maxLength": 9},
  "HM": {"code": "0", "num_code": "334", "minLength": 6, "maxLength": 6},
  "VA": {"code": "379", "num_code": "336", "minLength": 6, "maxLength": 6},
  "HN": {"code": "504", "num_code": "340", "minLength": 8, "maxLength": 9},
  "HK": {"code": "852", "num_code": "344", "minLength": 8, "maxLength": 9},
  "HU": {"code": "36", "num_code": "348", "minLength": 9, "maxLength": 9},
  "IS": {"code": "354", "num_code": "352", "minLength": 7, "maxLength": 9},
  "ID": {"code": "62", "num_code": "360", "minLength": 9, "maxLength": 12},
  "IR": {"code": "98", "num_code": "364", "minLength": 9, "maxLength": 12},
  "IQ": {"code": "964", "num_code": "368", "minLength": 9, "maxLength": 12},
  "IE": {"code": "353", "num_code": "372", "minLength": 9, "maxLength": 12},
  "IM": {"code": "44", "num_code": "833", "minLength": 9, "maxLength": 12},
  "IT": {"code": "39", "num_code": "380", "minLength": 9, "maxLength": 12},
  "JM": {"code": "1876", "num_code": "388", "minLength": 9, "maxLength": 12},
  "JP": {"code": "81", "num_code": "392", "minLength": 9, "maxLength": 12},
  "JE": {"code": "44", "num_code": "832", "minLength": 9, "maxLength": 12},
  "JO": {"code": "962", "num_code": "400", "minLength": 9, "maxLength": 12},
  "KZ": {"code": "7", "num_code": "398", "minLength": 9, "maxLength": 12},
  "KE": {"code": "254", "num_code": "404", "minLength": 9, "maxLength": 12},
  "KI": {"code": "686", "num_code": "296", "minLength": 9, "maxLength": 12},
  "KP": {"code": "850", "num_code": "408", "minLength": 9, "maxLength": 12},
  "KR": {"code": "82", "num_code": "410", "minLength": 9, "maxLength": 12},
  "KW": {"code": "965", "num_code": "414", "minLength": 9, "maxLength": 12},
  "KG": {"code": "996", "num_code": "417", "minLength": 9, "maxLength": 12},
  "LA": {"code": "856", "num_code": "418", "minLength": 9, "maxLength": 12},
  "LV": {"code": "371", "num_code": "428", "minLength": 9, "maxLength": 12},
  "LB": {"code": "961", "num_code": "422", "minLength": 9, "maxLength": 12},
  "LS": {"code": "266", "num_code": "426", "minLength": 9, "maxLength": 12},
  "LR": {"code": "231", "num_code": "430", "minLength": 9, "maxLength": 12},
  "LY": {"code": "218", "num_code": "434", "minLength": 9, "maxLength": 12},
  "LI": {"code": "423", "num_code": "438", "minLength": 9, "maxLength": 12},
  "LT": {"code": "370", "num_code": "440", "minLength": 9, "maxLength": 12},
  "LU": {"code": "352", "num_code": "442", "minLength": 9, "maxLength": 12},
  "MO": {"code": "853", "num_code": "446", "minLength": 9, "maxLength": 12},
  "MK": {"code": "389", "num_code": "807", "minLength": 9, "maxLength": 12},
  "MG": {"code": "261", "num_code": "450", "minLength": 9, "maxLength": 12},
  "MW": {"code": "265", "num_code": "454", "minLength": 9, "maxLength": 12},
  "MY": {"code": "60", "num_code": "458", "minLength": 9, "maxLength": 12},
  "MV": {"code": "960", "num_code": "462", "minLength": 9, "maxLength": 12},
  "ML": {"code": "223", "num_code": "466", "minLength": 9, "maxLength": 12},
  "MT": {"code": "356", "num_code": "470", "minLength": 9, "maxLength": 12},
  "MH": {"code": "692", "num_code": "584", "minLength": 9, "maxLength": 12},
  "MQ": {"code": "596", "num_code": "474", "minLength": 9, "maxLength": 12},
  "MR": {"code": "222", "num_code": "478", "minLength": 9, "maxLength": 12},
  "MU": {"code": "230", "num_code": "480", "minLength": 9, "maxLength": 12},
  "YT": {"code": "262", "num_code": "175", "minLength": 9, "maxLength": 12},
  "MX": {"code": "52", "num_code": "484", "minLength": 9, "maxLength": 12},
  "FM": {"code": "691", "num_code": "583", "minLength": 9, "maxLength": 12},
  "MD": {"code": "373", "num_code": "498", "minLength": 9, "maxLength": 12},
  "MC": {"code": "377", "num_code": "492", "minLength": 9, "maxLength": 12},
  "MN": {"code": "976", "num_code": "496", "minLength": 9, "maxLength": 12},
  "ME": {"code": "382", "num_code": "499", "minLength": 9, "maxLength": 12},
  "MS": {"code": "1664", "num_code": "500", "minLength": 9, "maxLength": 12},
  "MA": {"code": "212", "num_code": "504", "minLength": 9, "maxLength": 12},
  "MZ": {"code": "258", "num_code": "508", "minLength": 9, "maxLength": 12},
  "MM": {"code": "95", "num_code": "104", "minLength": 9, "maxLength": 12},
  "NA": {"code": "264", "num_code": "516", "minLength": 9, "maxLength": 12},
  "NR": {"code": "674", "num_code": "520", "minLength": 9, "maxLength": 12},
  "NP": {"code": "977", "num_code": "524", "minLength": 9, "maxLength": 12},
  "NL": {"code": "31", "num_code": "528", "minLength": 9, "maxLength": 12},
  "NC": {"code": "687", "num_code": "540", "minLength": 9, "maxLength": 12},
  "NZ": {"code": "64", "num_code": "554", "minLength": 9, "maxLength": 12},
  "NI": {"code": "505", "num_code": "558", "minLength": 9, "maxLength": 12},
  "NE": {"code": "227", "num_code": "562", "minLength": 9, "maxLength": 12},
  "NU": {"code": "683", "num_code": "570", "minLength": 9, "maxLength": 12},
  "NF": {"code": "672", "num_code": "574", "minLength": 9, "maxLength": 12},
  "MP": {"code": "1670", "num_code": "580", "minLength": 9, "maxLength": 12},
  "NO": {"code": "47", "num_code": "578", "minLength": 9, "maxLength": 12},
  "OM": {"code": "968", "num_code": "512", "minLength": 9, "maxLength": 12},
  "PW": {"code": "680", "num_code": "585", "minLength": 9, "maxLength": 12},
  "PS": {"code": "970", "num_code": "275", "minLength": 9, "maxLength": 12},
  "PA": {"code": "507", "num_code": "591", "minLength": 9, "maxLength": 12},
  "PG": {"code": "675", "num_code": "598", "minLength": 9, "maxLength": 12},
  "PY": {"code": "595", "num_code": "600", "minLength": 9, "maxLength": 12},
  "PE": {"code": "51", "num_code": "604", "minLength": 9, "maxLength": 12},
  "PN": {"code": "64", "num_code": "612", "minLength": 9, "maxLength": 12},
  "PL": {"code": "48", "num_code": "616", "minLength": 9, "maxLength": 12},
  "PT": {"code": "351", "num_code": "620", "minLength": 9, "maxLength": 12},
  "PR": {"code": "1939", "num_code": "630", "minLength": 9, "maxLength": 12},
  "QA": {"code": "974", "num_code": "634", "minLength": 9, "maxLength": 12},
  "RE": {"code": "262", "num_code": "638", "minLength": 9, "maxLength": 12},
  "RO": {"code": "40", "num_code": "642", "minLength": 9, "maxLength": 12},
  "RU": {"code": "7", "num_code": "643", "minLength": 9, "maxLength": 12},
  "RW": {"code": "250", "num_code": "646", "minLength": 9, "maxLength": 12},
  "BL": {"code": "590", "num_code": "652", "minLength": 9, "maxLength": 12},
  "SH": {"code": "290", "num_code": "654", "minLength": 9, "maxLength": 12},
  "KN": {"code": "1869", "num_code": "659", "minLength": 9, "maxLength": 12},
  "LC": {"code": "1758", "num_code": "662", "minLength": 9, "maxLength": 12},
  "MF": {"code": "590", "num_code": "663", "minLength": 9, "maxLength": 12},
  "PM": {"code": "508", "num_code": "666", "minLength": 9, "maxLength": 12},
  "VC": {"code": "1784", "num_code": "670", "minLength": 9, "maxLength": 12},
  "WS": {"code": "685", "num_code": "882", "minLength": 9, "maxLength": 12},
  "SM": {"code": "378", "num_code": "674", "minLength": 9, "maxLength": 12},
  "ST": {"code": "239", "num_code": "678", "minLength": 9, "maxLength": 12},
  "SN": {"code": "221", "num_code": "686", "minLength": 9, "maxLength": 12},
  "RS": {"code": "381", "num_code": "688", "minLength": 9, "maxLength": 12},
  "SC": {"code": "248", "num_code": "690", "minLength": 9, "maxLength": 12},
  "SL": {"code": "232", "num_code": "694", "minLength": 9, "maxLength": 12},
  "SG": {"code": "65", "num_code": "702", "minLength": 9, "maxLength": 12},
  "SK": {"code": "421", "num_code": "703", "minLength": 9, "maxLength": 12},
  "SI": {"code": "386", "num_code": "705", "minLength": 9, "maxLength": 12},
  "SB": {"code": "677", "num_code": "90", "minLength": 9, "maxLength": 12},
  "SO": {"code": "252", "num_code": "706", "minLength": 9, "maxLength": 12},
  "ZA": {"code": "27", "num_code": "710", "minLength": 9, "maxLength": 12},
  "GS": {"code": "500", "num_code": "239", "minLength": 9, "maxLength": 12},
  "SS": {"code": "211", "num_code": "728", "minLength": 9, "maxLength": 12},
  "ES": {"code": "34", "num_code": "724", "minLength": 9, "maxLength": 12},
  "LK": {"code": "94", "num_code": "144", "minLength": 9, "maxLength": 12},
  "SD": {"code": "249", "num_code": "729", "minLength": 9, "maxLength": 12},
  "SR": {"code": "597", "num_code": "740", "minLength": 9, "maxLength": 12},
  "SJ": {"code": "47", "num_code": "744", "minLength": 9, "maxLength": 12},
  "SZ": {"code": "268", "num_code": "748", "minLength": 9, "maxLength": 12},
  "SE": {"code": "46", "num_code": "752", "minLength": 9, "maxLength": 12},
  "CH": {"code": "41", "num_code": "756", "minLength": 9, "maxLength": 12},
  "SY": {"code": "963", "num_code": "760", "minLength": 9, "maxLength": 12},
  "TW": {"code": "886", "num_code": "158", "minLength": 9, "maxLength": 12},
  "TJ": {"code": "992", "num_code": "762", "minLength": 9, "maxLength": 12},
  "TZ": {"code": "255", "num_code": "834", "minLength": 9, "maxLength": 12},
  "TH": {"code": "66", "num_code": "764", "minLength": 9, "maxLength": 12},
  "TL": {"code": "670", "num_code": "626", "minLength": 9, "maxLength": 12},
  "TG": {"code": "228", "num_code": "768", "minLength": 9, "maxLength": 12},
  "TK": {"code": "690", "num_code": "772", "minLength": 9, "maxLength": 12},
  "TO": {"code": "676", "num_code": "776", "minLength": 9, "maxLength": 12},
  "TT": {"code": "1868", "num_code": "780", "minLength": 9, "maxLength": 12},
  "TN": {"code": "216", "num_code": "788", "minLength": 9, "maxLength": 12},
  "TR": {"code": "90", "num_code": "792", "minLength": 9, "maxLength": 12},
  "TM": {"code": "993", "num_code": "795", "minLength": 9, "maxLength": 12},
  "TC": {"code": "1649", "num_code": "796", "minLength": 9, "maxLength": 12},
  "TV": {"code": "688", "num_code": "798", "minLength": 9, "maxLength": 12},
  "UG": {"code": "256", "num_code": "800", "minLength": 9, "maxLength": 12},
  "UA": {"code": "380", "num_code": "804", "minLength": 9, "maxLength": 12},
  "AE": {"code": "971", "num_code": "784", "minLength": 9, "maxLength": 12},
  "GB": {"code": "44", "num_code": "826", "minLength": 9, "maxLength": 12},
  "UY": {"code": "598", "num_code": "858", "minLength": 9, "maxLength": 12},
  "UZ": {"code": "998", "num_code": "860", "minLength": 9, "maxLength": 12},
  "VU": {"code": "678", "num_code": "548", "minLength": 9, "maxLength": 12},
  "VE": {"code": "58", "num_code": "862", "minLength": 9, "maxLength": 12},
  "VN": {"code": "84", "num_code": "704", "minLength": 9, "maxLength": 12},
  "VG": {"code": "1284", "num_code": "92", "minLength": 9, "maxLength": 12},
  "VI": {"code": "1340", "num_code": "850", "minLength": 9, "maxLength": 12},
  "WF": {"code": "681", "num_code": "876", "minLength": 9, "maxLength": 12},
  "YE": {"code": "967", "num_code": "887", "minLength": 9, "maxLength": 12},
  "ZM": {"code": "260", "num_code": "894", "minLength": 9, "maxLength": 12},
  "ZW": {"code": "263", "num_code": "716", "minLength": 9, "maxLength": 12}
};
